### ISSUE TITLE
potential issue with mp_ephem 

### ISSUE THREAD

**Issue by nicoletanjy** [OSSOS/liborbfit#8]
I've been having trouble running alignImage_u.py, and the error seems to be mp_ephem related:
```
Traceback (most recent call last):
  File "alignImages_u.py", line 441, in <module>
    orb = mp_ephem.BKOrbit(observations)
  File "/Users/school/anaconda/envs/uband/lib/python2.7/site-packages/mp_ephem-0.9.2-py2.7-macosx-10.7-x86_64.egg/mp_ephem/bk_orbit.py", line 74, in __init__
    self._fit_radec()
  File "/Users/school/anaconda/envs/uband/lib/python2.7/site-packages/mp_ephem-0.9.2-py2.7-macosx-10.7-x86_64.egg/mp_ephem/bk_orbit.py", line 161, in _fit_radec
    _ = self.orbfit.fitradec(ctypes.c_char_p(bytes(_mpc_file.name, 'utf-8')),
TypeError: str() takes at most 1 argument (2 given)
```

For reference, I'm using macOS 10.14.6 and have gcc Apple LLVM version 10.0.1 installed.

**Comment by ijiraq** [comment]
I'm not able to see where this might be caused by a problem in mp_ephem.BKOrbit.  

if you share more of the code I might have some ideas.  The basic functionality is:

```
from mp_ephem import BKOrbit

orbit = BKOrbit(None, ast_filename='astrometry_file.mpc')
```

for example.

**Comment by nicoletanjy** [comment]
Here's where mp_ephem.BKOrbit appears in the code: 
```
    if not opt.sidereal:
        wcs=WCS.WCS(headers[0],mode='pyfits')

        with open('{}/{}.mpc'.format(opt.mpcPath, targetName)) as han:
            mpc_dat = han.readlines()

        observations = []
        for i in range(len(mpc_dat)):
            date = mpc_dat[i][15:31]
            s = mpc_dat[i][32:44].split()
            ra = 15.0*(float(s[0])+float(s[1])/60.0+float(s[2])/3600.0)
            s = mpc_dat[i][44:57].split()
            dec = abs(float(s[0]))+float(s[1])/60.0+float(s[2])/3600.0
            if '-' in s[0]:
                dec *= -1.0
            observations.append(mp_ephem.Observation(ra=ra, dec=dec, date=date, observatory_code = 568))
        #observations = np.array(observations)
        orb = mp_ephem.BKOrbit(observations)
```
It's from [alignImages_u.py](https://github.com/Col-OSSOS/ColOSSOS/blob/master/u-CFHT/alignImages_u.py) in the ColOSSOS repository.

**Comment by ijiraq** [comment]
I think that fragment of code should be changed.  I've made comment over in the ColOSSOS project.
